name: hello-world
on:  
  push:
    branches: [ main ]
  pull_request:
        branches: [ main ]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run:  echo "Welcome to github actions"
